In [1]:
import numpy as np
import pandas as pd
pd.__version__

'2.3.1'

## 2.1 文件的读取和写入

#### 1.文件读取

In [2]:
# 读取csv文件
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv")
df_csv

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [26]:
# 读取txt文件
df_txt = pd.read_table("data_base/data/ch2/my_table.txt")
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [4]:
# 读取excel文件
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx")
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.1公共参数

In [6]:
# 公共参数head
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",header=None)
de_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [7]:
# 公共参数index_col
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",index_col=['col1','col2'])
df_csv

           col3    col4      col5
col1 col2
2    a      1.4   apple  2020/1/1
3    b      3.4  banana  2020/1/2
6    c      2.5  orange  2020/1/5

In [8]:
# 公共参数usecols
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",usecols=['col1','col2'])
df_txt

   col1 col2
0     2    a
1     3    b
2     6    c

In [9]:
# 公共参数parse_dates
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",parse_dates=['col5'])
df_csv

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05

In [10]:
# 公共参数nrows
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx",nrows=3)
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.3 分隔参数

In [13]:
pd.read_table(
    'data_base/data/ch2/my_table_special_sep.txt',
    sep=r'\|\|\|\|',
    engine='python'
)

  col1                 col2
0   TS    This is an apple.
1   GQ      My name is Bob.
2   WT           Well done!

#### 2.2数据写入

In [23]:
# 去除索引
df_csv.to_csv('data_base/data/ch2/my_csv_saved.csv',index=False)
print(open('data_base/data/ch2/my_csv_saved.csv').read())

col1,col2,col3,col4,col5
2,a,1.4,apple,2020-01-01
3,b,3.4,banana,2020-01-02
6,c,2.5,orange,2020-01-05

In [27]:
# 制表
df_txt.to_csv('data_base/data/ch2/my_txt_saved.txt',sep='\t',index=False)
print(open('data_base/data/ch2/my_txt_saved.txt').read())

col1	col2	col3	col4	col5
2	a	1.4	apple	2020/1/1
3	b	3.4	banana	2020/1/2
6	c	2.5	orange	2020/1/5

In [28]:
# 转换成markdown
print(df_csv.to_markdown())

|    |   col1 | col2   |   col3 | col4   | col5                |
|---:|-------:|:-------|-------:|:-------|:--------------------|
|  0 |      2 | a      |    1.4 | apple  | 2020-01-01 00:00:00 |
|  1 |      3 | b      |    3.4 | banana | 2020-01-02 00:00:00 |
|  2 |      6 | c      |    2.5 | orange | 2020-01-05 00:00:00 |

In [29]:
# 转换成latex
print(df_csv.style.to_latex())

\begin{tabular}{lrlrll}
 & col1 & col2 & col3 & col4 & col5 \\
0 & 2 & a & 1.400000 & apple & 2020-01-01 00:00:00 \\
1 & 3 & b & 3.400000 & banana & 2020-01-02 00:00:00 \\
2 & 6 & c & 2.500000 & orange & 2020-01-05 00:00:00 \\
\end{tabular}