# 第三章：索引

## 3.1 单级索引

#### 1.DataFrame列索引

In [1]:
import numpy as np
import pandas as pd
import streamlit

df = pd.read_csv('data_base/data/learn_pandas.csv',
                 usecols=['School','Grade','Name','Gender','Weight','Transfer'])
df['Name'].head()

0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: object

In [4]:
df[['Name','Grade']].head()

             Name      Grade
0    Gaopeng Yang   Freshman
1  Changqiang You   Freshman
2         Mei Sun     Senior
3    Xiaojuan Sun  Sophomore
4     Gaojuan You  Sophomore

In [5]:
df.Gender.head()

0    Female
1      Male
2      Male
3    Female
4      Male
Name: Gender, dtype: object

#### 2.列索引

In [6]:
s = pd.Series([1,2,3,4,5,6],index=['a','b','a','a','a','c'])
s['a']

a    1
a    3
a    4
a    5
dtype: int64

In [8]:
s['b']

np.int64(2)

In [9]:
s['c':'b':-2]

c    6
a    4
b    2
dtype: int64

In [10]:
# 前后端点为非唯一值，需要排序
s.sort_index()['a':'b']

a    1
a    3
a    4
a    5
b    2
dtype: int64

In [11]:
# 整数切片（不包含右端点）
s[1:-1:2]

b    2
a    4
dtype: int64

#### 3.loc索引器

##### "*"为单个元素

In [18]:
df_demo = df.set_index(['Name'])
df_demo.head()

               School      Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A   Freshman  Female    46.0        N
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N
Gaojuan You         C  Sophomore    Male    74.0        N

In [13]:
df_demo.loc['Qiang Sun'] # 重复元素返回DataFrame

          School      Grade  Gender  Weight Transfer
Name
Qiang Sun      D     Junior  Female    53.0        N
Qiang Sun      D  Sophomore  Female    40.0        N
Qiang Sun      A     Junior  Female     NaN        N

In [15]:
df_demo.loc['Quan Zhao'] # 单一元素返回Series

School           A
Grade       Junior
Gender      Female
Weight        53.0
Transfer         N
Name: Quan Zhao, dtype: object

In [20]:
df_demo.loc['Quan Zhao','School']

'A'

##### 练一练：当两个“*”指代的行元素和列元素在DataFrame的行索引和列索引中都为重复值，此时结果是什么类型？

In [22]:
# DataFrame
df = pd.DataFrame([[1,2],[3,4]], columns=["A"]*2, index=["B"]*2)
df

   A  A
B  1  2
B  3  4

##### "*"为元素列表

In [23]:
df_demo.loc[['Qiang Sun','Quan Zhao'],['School','Grade']]

          School      Grade
Name
Qiang Sun      D     Junior
Qiang Sun      D  Sophomore
Qiang Sun      A     Junior
Quan Zhao      A     Junior

##### "*"为元素切片

In [24]:
df_loc_slice_demo = df_demo.copy()
df_loc_slice_demo.index = range(df_demo.shape[0],0,-1) # 将行号倒过来
df_loc_slice_demo.loc[5:3]

  School   Grade  Gender  Weight Transfer
5      C  Junior  Female    46.0        N
4      D  Senior  Female    50.0        N
3      A  Senior  Female    45.0        N

##### "*"为布尔列表

In [26]:
df_demo.loc[df_demo.Grade.isin(['Freshman','Senior'])].head()

               School     Grade  Gender  Weight Transfer
Name
Gaopeng Yang        A  Freshman  Female    46.0        N
Changqiang You      B  Freshman    Male    70.0        N
Mei Sun             A    Senior    Male    89.0        N
Xiaoli Qian         D  Freshman  Female    51.0        N
Qiang Chu           A  Freshman  Female    52.0        N

##### 练一练：
完成以下索引的相关操作：

* 选出A学校和B学校的大一女生。

* select_dtypes()是一个实用函数，它能够从表中选出或剔除相应类型的列。若要选出所有数值型的列，只需使用.select_dtypes(include='number')；若要剔除所有布尔类型和int64类型的列，只需使用.select_dtypes(exclude=['bool', 'int64'])。请利用布尔列表选择的方法结合DataFrame的dtypes属性在learn_pandas数据集上实现这个功能。

In [34]:
# 第一问
df = pd.read_csv('data_base/data/learn_pandas.csv')
res = df.loc[df.School.isin(['A','B']) & (df.Gender=='Female') & (df.Grade=='Freshman')]
res.head()

,School,Grade,Name,Gender,Height,Weight,Transfer,Test_Number,Test_Date,Time_Record
0,A,Freshman,Gaopeng Yang,Female,158.9,46.0,N,1,2019/10/5,0:04:34
6,A,Freshman,Qiang Chu,Female,162.5,52.0,N,1,2019/12/12,0:03:53
32,B,Freshman,Gaopeng Shi,Female,162.9,48.0,N,1,2019/9/12,0:04:58
45,B,Freshman,Quan Chu,Female,154.7,43.0,N,1,2019/11/28,0:04:47
57,B,Freshman,Changquan Chu,Female,159.6,45.0,N,2,2019/12/9,0:04:18

In [38]:
# 第二问
df.loc[:,(df.dtypes =='int64')
|(df.dtypes =='int32')
|(df.dtypes =='float64')
|(df.dtypes =='float32')] #等价于select_dtypes('number')

     Height  Weight  Test_Number
0     158.9    46.0            1
1     166.5    70.0            1
2     188.9    89.0            2
3       NaN    41.0            2
4     174.0    74.0            2
..      ...     ...          ...
195   153.9    46.0            2
196   160.9    50.0            3
197   153.9    45.0            1
198   175.3    71.0            2
199   155.7    51.0            1

[200 rows x 3 columns]

In [39]:
df.loc[:,(df.dtypes !='bool') & (df.dtypes !='int64')]

,School,Grade,Name,Gender,Height,Weight,Transfer,Test_Date,Time_Record
0,A,Freshman,Gaopeng Yang,Female,158.9,46.0,N,2019/10/5,0:04:34
1,B,Freshman,Changqiang You,Male,166.5,70.0,N,2019/9/4,0:04:20
2,A,Senior,Mei Sun,Male,188.9,89.0,N,2019/9/12,0:05:22
3,C,Sophomore,Xiaojuan Sun,Female,NaN,41.0,N,2020/1/3,0:04:08
4,C,Sophomore,Gaojuan You,Male,174.0,74.0,N,2019/11/6,0:05:22
...,...,...,...,...,...,...,...,...,...
195,C,Junior,Xiaojuan Sun,Female,153.9,46.0,N,2019/10/17,0:04:31
196,D,Senior,Li Zhao,Female,160.9,50.0,N,2019/9/22,0:04:03
197,A,Senior,Chengqiang Chu,Female,153.9,45.0,N,2020/1/5,0:04:48
198,A,Senior,Chengmei Shen,Male,175.3,71.0,N,2020/1/7,0:04:58
199,D,Sophomore,Chunpeng Lv,Male,155.7,51.0,N,2019/11/6,0:05:05

In [40]:
# 对行或列赋值
df_chain = pd.DataFrame([[0,0],[1,0],[-1,0]],columns=list('AB'))
df_chain

   A  B
0  0  0
1  1  0
2 -1  0

In [41]:
df_chain.loc[df_chain.A!=0,'B'] = 1
df_chain

   A  B
0  0  0
1  1  1
2 -1  1

#### 4.iloc索引器

In [44]:
import numpy as np

df_demo.iloc[np.isin(np.arange(df_demo.shape[0]),[1,2,3])]

               School      Grade  Gender  Weight Transfer
Name
Changqiang You      B   Freshman    Male    70.0        N
Mei Sun             A     Senior    Male    89.0        N
Xiaojuan Sun        C  Sophomore  Female    41.0        N

In [45]:
# 必须要传入布尔序列的values
df_demo.iloc[(df_demo.Weight>80).values].head()

               School      Grade Gender  Weight Transfer
Name
Mei Sun             A     Senior   Male    89.0        N
Qiang Zheng         A     Senior   Male    87.0        N
Qiang Han           B   Freshman   Male    87.0        N
Chengpeng Zhou      C     Senior   Male    81.0        N
Feng Han            A  Sophomore   Male    82.0        N

In [52]:
# 索引单个元素是可以用.at[]&.iat[],性能更好
df_demo.iat[1,1]

'Freshman'

In [53]:
df_demo.at['Qiang Zheng','Weight']

np.float64(87.0)

#### 5.query()函数

##### 练一练：
利用query()选出A学校和B学校的大一女生。

In [54]:
df.query('(School in ["A","B"]) and '
         '(Gender=="Female") and '
         '(Grade=="Freshman")').head()

,School,Grade,Name,Gender,Height,Weight,Transfer,Test_Number,Test_Date,Time_Record
0,A,Freshman,Gaopeng Yang,Female,158.9,46.0,N,1,2019/10/5,0:04:34
6,A,Freshman,Qiang Chu,Female,162.5,52.0,N,1,2019/12/12,0:03:53
32,B,Freshman,Gaopeng Shi,Female,162.9,48.0,N,1,2019/9/12,0:04:58
45,B,Freshman,Quan Chu,Female,154.7,43.0,N,1,2019/11/28,0:04:47
57,B,Freshman,Changquan Chu,Female,159.6,45.0,N,2,2019/12/9,0:04:18

In [56]:
# 列表的比较(==/!=) -> is in/not in
df.query('Grade == ["Junior","Senior"]').head()

,School,Grade,Name,Gender,Height,Weight,Transfer,Test_Number,Test_Date,Time_Record
2,A,Senior,Mei Sun,Male,188.9,89.0,N,2,2019/9/12,0:05:22
7,D,Junior,Gaoqiang Qian,Female,161.9,50.0,N,1,2019/9/3,0:03:45
9,B,Junior,Juan Xu,Female,164.8,NaN,N,3,2019/10/5,0:04:05
11,D,Junior,Xiaoquan Lv,Female,153.2,43.0,N,2,2019/9/16,0:04:49
12,A,Senior,Peng You,Female,NaN,48.0,NaN,2,2019/10/20,0:04:10

In [57]:
# "@" 引用外部变量
query_list = ["Junior","Senior"]
df.query('Grade == @query_list').head()

,School,Grade,Name,Gender,Height,Weight,Transfer,Test_Number,Test_Date,Time_Record
2,A,Senior,Mei Sun,Male,188.9,89.0,N,2,2019/9/12,0:05:22
7,D,Junior,Gaoqiang Qian,Female,161.9,50.0,N,1,2019/9/3,0:03:45
9,B,Junior,Juan Xu,Female,164.8,NaN,N,3,2019/10/5,0:04:05
11,D,Junior,Xiaoquan Lv,Female,153.2,43.0,N,2,2019/9/16,0:04:49
12,A,Senior,Peng You,Female,NaN,48.0,NaN,2,2019/10/20,0:04:10

#### 4.索引运算

In [58]:
df_set_1 = pd.DataFrame([[0,1],[2,3],[4,5]],
                        index=pd.Index(['a','b','a'],name='id_1'))

      0  1
id_1
a     0  1
b     2  3
a     4  5

In [59]:
df_set_2 = pd.DataFrame([[4,5],[2,6],[7,1]],
                        index=pd.Index(['b','b','c'],name='id_2'))
df_set_2

      0  1
id_2
b     4  5
b     2  6
c     7  1

In [61]:
df_set_in_col_1 = df_set_1.reset_index()
df_set_in_col_1

  id_1  0  1
0    a  0  1
1    b  2  3
2    a  4  5

In [62]:
df_set_in_col_2 = df_set_2.reset_index()
df_set_in_col_2

  id_2  0  1
0    b  4  5
1    b  2  6
2    c  7  1

In [63]:
# 两张表要比的那一列还没设成索引时，用 isin 也能做“交集筛选”
df_set_in_col_1[df_set_in_col_1.id_1.isin(df_set_in_col_2.id_2)]

  id_1  0  1
1    b  2  3

## 3.2多级索引

#### 1.构造多级索引

##### 练一练：3.2.1节开头处利用from_product构造了df_multi，请分别利用from_tuples和from_arrays构造一个相同的DataFrame。

In [9]:
import numpy as np

np.random.seed(0)
df_ = df.copy()

my_tuple_1 = [('A','Male'),('A','Female'),('B','Male'),('B','Female'),
 ('C','Male'),('C','Female'),('D','Male'),('D','Female')]
multi_index = pd.MultiIndex.from_tuples(my_tuple_1,names=('School','Gender'))
df_.Grade = df_.Grade.map(
    {"Freshman": 1, "Sophomore": 2, "Junior": 3, "Senior": 4}
)
my_tuple_2 = [('Height',1),('Height',2),('Height',3),('Height',4),('Weight',1),('Weight',2),('Weight',3),('Weight',4)]
multi_columns = pd.MultiIndex.from_tuples(my_tuple_2,names=('Indicator','Grade'))

# 构造DataFrame内容是照搬书上的代码
df_multi = pd.DataFrame(
    np.c_[(np.random.randn(8,4)*5 + 163).tolist(),
    (np.random.randn(8,4)*5 + 65).tolist()],index=multi_index,
    columns=multi_columns).round(1).sort_values(["Indicator","Grade"],axis=1)
df_multi

Indicator     Height                      Weight
Grade              1      2      3      4      1     2     3     4
School Gender
A      Male    171.8  165.0  167.9  174.2   60.6  55.1  63.3  65.8
       Female  172.3  158.1  167.8  162.2   71.2  71.0  63.1  63.5
B      Male    162.5  165.1  163.7  170.3   59.8  57.9  56.5  74.8
       Female  166.8  163.6  165.2  164.7   62.5  62.8  58.7  68.9
C      Male    170.5  162.0  164.6  158.7   56.9  63.9  60.5  66.9
       Female  150.2  166.3  167.3  159.3   62.4  59.1  64.9  67.1
D      Male    174.3  155.7  163.2  162.1   65.3  66.5  61.8  63.2
       Female  170.7  170.3  163.8  164.9   61.6  63.2  60.9  56.4

#### 2.多级索引的loc索引器

## 3.3常用索引方法

#### 1.索引层的交换和删除

In [10]:
import pandas as pd
import numpy as np

np.random.seed(0)
L1,L2,L3 = ['A','B'],['a','b'],['alpha','beta']
my_index1 = pd.MultiIndex.from_product([L1,L2,L3],
                                       names = ('Upper','Lower','Extra'))
L4,L5,L6 = ['C','D'],['c','d'],['cat','dog']
my_index2 = pd.MultiIndex.from_product([L4,L5,L6],
                                       names = ('Big','Small','Other'))
df_ex = pd.DataFrame(np.random.randint(-9,10,(8,8),),
                     index = my_index1,
                     columns= my_index2)
df_ex

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9
            beta   -9  -5  -4  -3  -1   8   6  -5
      b     alpha   0   1  -8  -8  -2   0  -6  -3
            beta    2   5   9  -9   5  -6   3   1

##### swaplevel方法（只能交换两层）

In [11]:
df_ex.swaplevel(0,2,axis = 1).head() #列索引交换

Other             cat dog cat dog cat dog cat dog
Small               c   c   d   d   c   c   d   d
Big                 C   C   C   C   D   D   D   D
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9

##### reorder_levels方法

In [12]:
df_ex.reorder_levels([2,0,1],axis=0).head() # 行索引交换

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Extra Upper Lower
alpha A     a       3   6  -9  -6  -6  -2   0   9
beta  A     a      -5  -3   3  -8  -3  -2   5   8
alpha A     b      -4   4  -1   0   7  -4   6   6
beta  A     b      -9   9  -6   8   5  -2  -9  -8
alpha B     a       0  -9   1  -6   2   9  -7  -9

##### 删除索引

In [13]:
df_ex.droplevel(1,axis=1).head()

Big                 C               D
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     alpha   3   6  -9  -6  -6  -2   0   9
            beta   -5  -3   3  -8  -3  -2   5   8
      b     alpha  -4   4  -1   0   7  -4   6   6
            beta   -9   9  -6   8   5  -2  -9  -8
B     a     alpha   0  -9   1  -6   2   9  -7  -9

In [14]:
df_ex.droplevel([0,1],axis=0).head()

Big     C               D
Small   c       d       c       d
Other cat dog cat dog cat dog cat dog
Extra
alpha   3   6  -9  -6  -6  -2   0   9
beta   -5  -3   3  -8  -3  -2   5   8
alpha  -4   4  -1   0   7  -4   6   6
beta   -9   9  -6   8   5  -2  -9  -8
alpha   0  -9   1  -6   2   9  -7  -9

#### 2.索引属性的修改

In [15]:
# rename_axis()
df_ex.rename_axis(index={'Upper':'Changed_row'})

Big                       C               D
Small                     c       d       c       d
Other                   cat dog cat dog cat dog cat dog
Changed_row Lower Extra
A           a     alpha   3   6  -9  -6  -6  -2   0   9
                  beta   -5  -3   3  -8  -3  -2   5   8
            b     alpha  -4   4  -1   0   7  -4   6   6
                  beta   -9   9  -6   8   5  -2  -9  -8
B           a     alpha   0  -9   1  -6   2   9  -7  -9
                  beta   -9  -5  -4  -3  -1   8   6  -5
            b     alpha   0   1  -8  -8  -2   0  -6  -3
                  beta    2   5   9  -9   5  -6   3   1

In [16]:
# rename()
df_ex.rename(columns={'cat':'not cat'},level=2).head()

Big                     C                       D
Small                   c           d           c           d
Other             not cat dog not cat dog not cat dog not cat dog
Upper Lower Extra
A     a     alpha       3   6      -9  -6      -6  -2       0   9
            beta       -5  -3       3  -8      -3  -2       5   8
      b     alpha      -4   4      -1   0       7  -4       6   6
            beta       -9   9      -6   8       5  -2      -9  -8
B     a     alpha       0  -9       1  -6       2   9      -7  -9

In [18]:
# 参数值为函数
df_ex.rename(index=lambda x:str.upper(x),level=2).head()

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     ALPHA   3   6  -9  -6  -6  -2   0   9
            BETA   -5  -3   3  -8  -3  -2   5   8
      b     ALPHA  -4   4  -1   0   7  -4   6   6
            BETA   -9   9  -6   8   5  -2  -9  -8
B     a     ALPHA   0  -9   1  -6   2   9  -7  -9

In [19]:
# 对索引整个元素的替换
new_values = iter(list('abcdefgh'))
df_ex.rename(index=lambda x:next(new_values),level=2).head()

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     a       3   6  -9  -6  -6  -2   0   9
            b      -5  -3   3  -8  -3  -2   5   8
      b     c      -4   4  -1   0   7  -4   6   6
            d      -9   9  -6   8   5  -2  -9  -8
B     a     e       0  -9   1  -6   2   9  -7  -9

In [21]:
# map方法
df_temp = df_ex.copy()
df_temp.index = df_temp.index.map(lambda x:(x[0],x[1],str.upper(x[2])))
df_temp.head()

Big                 C               D
Small               c       d       c       d
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra
A     a     ALPHA   3   6  -9  -6  -6  -2   0   9
            BETA   -5  -3   3  -8  -3  -2   5   8
      b     ALPHA  -4   4  -1   0   7  -4   6   6
            BETA   -9   9  -6   8   5  -2  -9  -8
B     a     ALPHA   0  -9   1  -6   2   9  -7  -9

In [26]:
# 多级索引的压缩
df_temp = df_ex.copy()
df_temp.index = df_temp.index.map(lambda x:(x[0]+'-'+x[1]+'-'+x[2]))
df_temp.head()

Big         C               D
Small       c       d       c       d
Other     cat dog cat dog cat dog cat dog
A-a-alpha   3   6  -9  -6  -6  -2   0   9
A-a-beta   -5  -3   3  -8  -3  -2   5   8
A-b-alpha  -4   4  -1   0   7  -4   6   6
A-b-beta   -9   9  -6   8   5  -2  -9  -8
B-a-alpha   0  -9   1  -6   2   9  -7  -9

In [27]:
# 展开
new_idx = df_temp.index.map(lambda x:tuple(x.split('-')))
df_temp.index = new_idx
df_temp.head()

Big         C               D
Small       c       d       c       d
Other     cat dog cat dog cat dog cat dog
A a alpha   3   6  -9  -6  -6  -2   0   9
    beta   -5  -3   3  -8  -3  -2   5   8
  b alpha  -4   4  -1   0   7  -4   6   6
    beta   -9   9  -6   8   5  -2  -9  -8
B a alpha   0  -9   1  -6   2   9  -7  -9

##### 练一练：将上述df_temp的内层列索引合并到与外层列索引（用下划线连接）后删除内层行索引，即结果表压缩为两层列索引，同时再把外层行索引的索引名重命名为“Big_Other”。

In [28]:
df_temp.columns = df_temp.columns.map(lambda x:(x[0]+'_'+x[2],x[1],x[2]))
df_temp.droplevel(-1,axis=1).rename_axis(columns = {'Big':'Big_Other'}).head()

Big_Other C_cat C_dog C_cat C_dog D_cat D_dog D_cat D_dog
Small         c     c     d     d     c     c     d     d
A a alpha     3     6    -9    -6    -6    -2     0     9
    beta     -5    -3     3    -8    -3    -2     5     8
  b alpha    -4     4    -1     0     7    -4     6     6
    beta     -9     9    -6     8     5    -2    -9    -8
B a alpha     0    -9     1    -6     2     9    -7    -9

#### 3.索引的重置

In [29]:
# set_index(''),关键参数append
df_new = pd.DataFrame({'A':list('abcd'),'B':list('EFGH'),'C':1234})
df_new.set_index('A')

   B     C
A
a  E  1234
b  F  1234
c  G  1234
d  H  1234

In [30]:
df_new.set_index('A',append=True)

     B     C
  A
0 a  E  1234
1 b  F  1234
2 c  G  1234
3 d  H  1234

In [37]:
my_idx = pd.Series(list('WXYZ'),name = 'D')
df_new = df_new.set_index(['A',my_idx])
df_new

     B     C
A D
a W  E  1234
b X  F  1234
c Y  G  1234
d Z  H  1234

In [38]:
# reset_index(),关键参数drop，是否删除索引
df_new.reset_index(['D'])

   D  B     C
A
a  W  E  1234
b  X  F  1234
c  Y  G  1234
d  Z  H  1234

In [39]:
df_new.reset_index(['D'],drop=True)

   B     C
A
a  E  1234
b  F  1234
c  G  1234
d  H  1234

#### 4.索引的对齐

In [40]:
# reindex
df_reindex = pd.DataFrame({'Weight':[60,70,80],
                          'Height': [160,170,180]},
                          index=['1001','1003','1002'])
df_reindex

      Weight  Height
1001      60     160
1003      70     170
1002      80     180

In [43]:
df_reindex.reindex(index=['1001','1002','1003','1004'],
                   columns=['Weight','Gender'])

      Weight  Gender
1001    60.0     NaN
1002    80.0     NaN
1003    70.0     NaN
1004     NaN     NaN