In [3]:
import numpy as np
import pandas as pd

from base.practice5 import index

pd.__version__

'2.3.1'

## 2.1 文件的读取和写入

#### 1.文件读取

In [4]:
# 读取csv文件
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv")
df_csv

   col1 col2  col3    col4        col5
0     2    a   1.4   apple  2020-01-01
1     3    b   3.4  banana  2020-01-02
2     6    c   2.5  orange  2020-01-05

In [26]:
# 读取txt文件
df_txt = pd.read_table("data_base/data/ch2/my_table.txt")
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [4]:
# 读取excel文件
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx")
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.1公共参数

In [6]:
# 公共参数head
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",header=None)
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [7]:
# 公共参数index_col
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",index_col=['col1','col2'])
df_csv

           col3    col4      col5
col1 col2
2    a      1.4   apple  2020/1/1
3    b      3.4  banana  2020/1/2
6    c      2.5  orange  2020/1/5

In [8]:
# 公共参数usecols
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",usecols=['col1','col2'])
df_txt

   col1 col2
0     2    a
1     3    b
2     6    c

In [9]:
# 公共参数parse_dates
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",parse_dates=['col5'])
df_csv

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05

In [10]:
# 公共参数nrows
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx",nrows=3)
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.3 分隔参数

In [13]:
pd.read_table(
    'data_base/data/ch2/my_table_special_sep.txt',
    sep=r'\|\|\|\|',
    engine='python'
)

  col1                 col2
0   TS    This is an apple.
1   GQ      My name is Bob.
2   WT           Well done!

#### 2.2数据写入

In [23]:
# 去除索引
df_csv.to_csv('data_base/data/ch2/my_csv_saved.csv',index=False)
print(open('data_base/data/ch2/my_csv_saved.csv').read())

col1,col2,col3,col4,col5
2,a,1.4,apple,2020-01-01
3,b,3.4,banana,2020-01-02
6,c,2.5,orange,2020-01-05

In [27]:
# 制表
df_txt.to_csv('data_base/data/ch2/my_txt_saved.txt',sep='\t',index=False)
print(open('data_base/data/ch2/my_txt_saved.txt').read())

col1	col2	col3	col4	col5
2	a	1.4	apple	2020/1/1
3	b	3.4	banana	2020/1/2
6	c	2.5	orange	2020/1/5

In [28]:
# 转换成markdown
print(df_csv.to_markdown())

|    |   col1 | col2   |   col3 | col4   | col5                |
|---:|-------:|:-------|-------:|:-------|:--------------------|
|  0 |      2 | a      |    1.4 | apple  | 2020-01-01 00:00:00 |
|  1 |      3 | b      |    3.4 | banana | 2020-01-02 00:00:00 |
|  2 |      6 | c      |    2.5 | orange | 2020-01-05 00:00:00 |

In [6]:
# 转换成latex
print(df_csv.style.to_latex())

\begin{tabular}{lrlrll}
 & col1 & col2 & col3 & col4 & col5 \\
0 & 2 & a & 1.400000 & apple & 2020-01-01 \\
1 & 3 & b & 3.400000 & banana & 2020-01-02 \\
2 & 6 & c & 2.500000 & orange & 2020-01-05 \\
\end{tabular}

## 2.2 基本数据结构

#### 1.Series

In [8]:
# 创建Series对象
s = pd.Series(
    data = [100,'a',{'dic1':5}],
    index = pd.Index(['id1',20,'third'],name='my_index'),
    dtype = 'object',
    name = 'my_name'
)
s

my_index
id1              100
20                 a
third    {'dic1': 5}
Name: my_name, dtype: object

In [10]:
# 获取属性内容
s.values

Index(['id1', 20, 'third'], dtype='object', name='my_index')

In [11]:
s.index

Index(['id1', 20, 'third'], dtype='object', name='my_index')

In [12]:
s.dtype

dtype('O')

In [13]:
s.name

'my_name'

In [14]:
# 获取序列长度
s.shape

(3,)

In [15]:
# 索引取值
s['third']

{'dic1': 5}

#### 2.DataFrame

In [16]:
df = pd.DataFrame(
    data={
        'col_0':[1,2,3],
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=[f'row_{i}' for i in range(3)]
)
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

##### 练一练：在上面的df中，如果data字典中'col_0'键对应的不是列表，而是1个索引与df中索引相同的Series，此时会发生什么？如果它的索引和df的索引不一致，又会发生什么？

In [24]:
# 当索引一致时，序列的值直接对应填入DataFrame。
index = [f'row_{i}' for i in range(3)]
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=index),
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [19]:
# 当索引不一致时且Series中索引值唯一时，当前DataFrame行索引如果在Series中出现，
# 则用Series对应元素填充，否则设为缺失值。
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=['row_3','row_2','row_1']), # Nan、3、2
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df

       col_0 col_1  col_2
row_0    NaN     a    1.2
row_1    3.0     b    2.2
row_2    2.0     c    3.2

In [20]:
# 用[col_name]和[col_list]取出相应的列与由多个列组成的新的DataFrame
df['col_0']

row_0    NaN
row_1    3.0
row_2    2.0
Name: col_0, dtype: float64

In [22]:
# New DataFrame
df[['col_0','col_1']]

       col_0 col_1
row_0    NaN     a
row_1    3.0     b
row_2    2.0     c

##### 练一练：df['col_0']和df[['col_0']]二者得到的结果类型有什么区别？

In [23]:
# 前者是Series，后者是DataFrame
df[['col_0']]

       col_0
row_0    NaN
row_1    3.0
row_2    2.0

In [25]:
# 把序列转换为列数为1的DataFrame
df['col_0'].to_frame()

       col_0
row_0      1
row_1      2
row_2      3

In [26]:
# 对DataFrame的行列进行转置
df.T

      row_0 row_1 row_2
col_0     1     2     3
col_1     a     b     c
col_2   1.2   2.2   3.2

##### 练一练：给定一个DataFrame，请构造其转置且不得使用“.T”。

In [30]:
df = pd.DataFrame(data={'A':[1,2,3],'B':[4,5,6]},index=list('abc'))
df_T = pd.DataFrame(df.values.T, index=df.columns, columns=df.index)
df.T.equals(df_T)

   a  b  c
A  1  2  3
B  4  5  6

##### 修改或删除列

In [36]:
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=index), # Nan、3、2
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df["col_0"] = df['col_0'].values[::-1] #颠倒顺序
df["col_2"] *= 2
df["col_3"] = ["apple","banana","cat"] #新增一列
df

       col_0 col_1  col_2   col_3
row_0      3     a    2.4   apple
row_1      2     b    4.4  banana
row_2      1     c    6.4     cat

In [37]:
# 删除列
df.drop(["col_3"],axis=1)

       col_0 col_1  col_2
row_0      3     a    2.4
row_1      2     b    4.4
row_2      1     c    6.4

In [38]:
# 删除行
df.drop(["row_1"],axis=0)

       col_0 col_1  col_2  col_3
row_0      3     a    2.4  apple
row_2      1     c    6.4    cat

## 2.3常用基本函数

#### 1.汇总函数

In [33]:
import pandas as pd

df = pd.read_csv('data_base/data/learn_pandas.csv')
df.columns

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='object')

In [34]:
df = df[df.columns[:7]]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   School    200 non-null    object
 1   Grade     200 non-null    object
 2   Name      200 non-null    object
 3   Gender    200 non-null    object
 4   Height    183 non-null    float64
 5   Weight    189 non-null    float64
 6   Transfer  188 non-null    object
dtypes: float64(2), object(5)
memory usage: 11.1+ KB

In [6]:
df.describe()

           Height      Weight
count  183.000000  189.000000
mean   163.218033   55.015873
std      8.608879   12.824294
min    145.400000   34.000000
25%    157.150000   46.000000
50%    161.900000   51.000000
75%    167.500000   65.000000
max    193.900000   89.000000

#### 2.特征统计函数

In [7]:
df_demo = df[['Height','Weight']]
df_demo.max()

Height    193.9
Weight     89.0
dtype: float64

In [8]:
df_demo.mean()

Height    163.218033
Weight     55.015873
dtype: float64

In [9]:
df_demo.quantile(0.75)

Height    167.5
Weight     65.0
Name: 0.75, dtype: float64

In [11]:
df_demo.idxmax() #最大值对应的索引

Height    193
Weight      2
dtype: int64

##### 练一练：身体质量指数BMI的计算方式是体重（单位为kg）除以身高（单位为m）的平方，请找出具有最高BMI指数对应同学的姓名。

In [13]:
df.T[(df.Weight / (df.Height / 100 ) ** 2).idxmax()]['Name']

'Chengpeng Zhou'

#### 3.频次函数

In [15]:
df.School.unique()
df['School'].nunique()

4

In [16]:
df['School'].value_counts()

School
D    69
A    57
C    40
B    34
Name: count, dtype: int64

In [17]:
df['School'].value_counts(normalize=True)

School
D    0.345
A    0.285
C    0.200
B    0.170
Name: proportion, dtype: float64

In [18]:
# 观察多个列组合的唯一值
df_demo = df[['Gender','Transfer','Name']]
df_demo.drop_duplicates(['Gender','Name'])

     Gender Transfer            Name
0    Female        N    Gaopeng Yang
1      Male        N  Changqiang You
2      Male        N         Mei Sun
3    Female        N    Xiaojuan Sun
4      Male        N     Gaojuan You
..      ...      ...             ...
194  Female      NaN     Yanmei Qian
196  Female        N         Li Zhao
197  Female        N  Chengqiang Chu
198    Male        N   Chengmei Shen
199    Male        N     Chunpeng Lv

[181 rows x 3 columns]

In [20]:
# 关键参数keep
df_demo.drop_duplicates(['Gender','Transfer'],keep='last')

     Gender Transfer            Name
147    Male      NaN        Juan You
150    Male        Y   Chengpeng You
169  Female        Y   Chengquan Qin
194  Female      NaN     Yanmei Qian
197  Female        N  Chengqiang Chu
199    Male        N     Chunpeng Lv

In [21]:
# keep设为False代表只出现过一次的行
df_demo.drop_duplicates(['Name','Gender'],keep=False).head()

   Gender Transfer            Name
0  Female        N    Gaopeng Yang
1    Male        N  Changqiang You
2    Male        N         Mei Sun
4    Male        N     Gaojuan You
5  Female        N     Xiaoli Qian

In [22]:
# duplicated()查重
df_demo.duplicated(['Gender','Transfer'])

0      False
1      False
2       True
3       True
4       True
       ...
195     True
196     True
197     True
198     True
199     True
Length: 200, dtype: bool

In [23]:
df['School'].duplicated().head()

0    False
1    False
2     True
3    False
4     True
Name: School, dtype: bool

#### 4.替换函数

##### 映射替换

In [8]:
# replace()函数替换
df['Gender'].replace({'Female':0,'Male':1}).astype(int).head()

/var/folders/qz/sxl6t5150772tp8x0p4g44mh0000gn/T/ipykernel_59573/1457946928.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Female':0,'Male':1}).astype(int).head()

0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64

In [7]:
df['Gender'].replace({'Female': 0, 'Male': 1}).astype(int).head()

/var/folders/qz/sxl6t5150772tp8x0p4g44mh0000gn/T/ipykernel_59573/3538262359.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Female': 0, 'Male': 1}).astype(int).head()

0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64

In [10]:
# 特殊方向替换.ffill()&.bfill()
s.replace([1,2],pd.NA).ffill()

0    a
1    a
2    b
3    b
4    b
5    b
6    a
dtype: object

In [11]:
s.replace([1,2],pd.NA).bfill()

0    a
1    b
2    b
3    a
4    a
5    a
6    a
dtype: object

##### 逻辑替换

In [12]:
# where()&mask()
s = pd.Series([-1,1.234,100,-50])
s.where(s<0) # 条件为False替换

0    -1.0
1     NaN
2     NaN
3   -50.0
dtype: float64

In [13]:
s.mask(s<0) # 条件为True替换

0        NaN
1      1.234
2    100.000
3        NaN
dtype: float64

In [14]:
# 条件只需要是布尔序列即可，但是索引要与被调用的Series相同
s_condition = pd.Series([True,False,False,True],index=s.index)
s.mask(s_condition)

0        NaN
1      1.234
2    100.000
3        NaN
dtype: float64

##### 数值替换

In [16]:
# round()、asb()&clip()
s.round(2)

0     -1.00
1      1.23
2    100.00
3    -50.00
dtype: float64

In [17]:
s.abs()

0      1.000
1      1.234
2    100.000
3     50.000
dtype: float64

In [18]:
s.clip(0,2)

0    0.000
1    1.234
2    2.000
3    0.000
dtype: float64

##### 练一练：在clip()中，超过边界的只能截断为边界值，如果要把超出边界的替换为自定义的值，可以如何做？

In [20]:
import numpy as np

s = pd.Series(np.arange(5))
s.clip(1,3)

0    1
1    1
2    2
3    3
4    3
dtype: int64

In [21]:
s.where(s>1,30).where(s<3,500)

0     30
1     30
2      2
3    500
4    500
dtype: int64

#### 5.排序函数

In [27]:
df_demo = df[['Grade','Name','Height','Weight']].set_index(['Grade','Name'])

In [23]:
# 值排序函数
df_demo.sort_values('Height').head()

                   Grade           Name
Height Weight
145.4  34.0       Junior     Xiaoli Chu
147.3  34.0       Senior      Gaomei Lv
147.8  34.0    Sophomore       Peng Han
148.7  41.0       Senior     Changli Lv
150.5  40.0    Sophomore  Changjuan You

In [25]:
df_demo.sort_values(['Height','Weight'],ascending=[False,True]).head()

                  Grade           Name
Height Weight
193.9  79.0      Senior  Xiaoqiang Qin
188.9  89.0      Senior        Mei Sun
186.5  83.0      Senior     Gaoli Zhao
185.3  87.0    Freshman      Qiang Han
183.9  87.0      Senior    Qiang Zheng

In [28]:
# 索引排序函数
df_demo.sort_index(level=['Grade','Name'],ascending=[True,False]).head()

                        Height  Weight
Grade    Name
Freshman Yanquan Wang    163.5    55.0
         Yanqiang Xu     152.4    38.0
         Yanqiang Feng   162.3    51.0
         Yanpeng Lv        NaN    65.0
         Yanli Zhang     165.1    52.0

In [30]:
# rank()函数
s = pd.Series(list('abac'))
df_rank = pd.DataFrame()
for method in ["average", "min", "max", "first", "dense"]:
    df_rank[method] = s.rank(method=method) # 将rank结果放入df_rank中
df_rank

   average  min  max  first  dense
0      1.5  1.0  2.0    1.0    1.0
1      3.0  3.0  3.0    3.0    2.0
2      1.5  1.0  2.0    2.0    1.0
3      4.0  4.0  4.0    4.0    3.0

#### 6.apply()函数

In [36]:
# 逐行迭代或者逐列迭代
df_demo = df[['Height','Weight']] # 取多列要用两个[]
df_demo.apply(lambda x:x.mean())

Height    163.218033
Weight     55.015873
dtype: float64

In [37]:
# 逐列迭代
df_demo.apply(lambda x:x.mean(),axis=1).head()

0    102.45
1    118.25
2    138.95
3     41.00
4    124.00
dtype: float64

## 2.4窗口

#### 1.滑动窗口

##### 练一练：在Numpy中也有一个同名函数np.diff()，它与pandas中的diff功能相同吗？请查阅文档说明。

In [ ]:
#两者都在算「差分」，但：
# 默认相邻差：结果数值接近，pandas 会多出开头的 NaN
# n=2 / periods=2：含义不同，不能当成同一个函数用
# 记法：NumPy 的 n 是「做几遍」；pandas 的 periods 是「隔几格」。

In [38]:
s = pd.Series([1,2,3,4,5])
s.rolling(3).apply(lambda x:list(x)[0])

0    NaN
1    NaN
2    1.0
3    2.0
4    3.0
dtype: float64

In [39]:
# 类滑窗函数shift()
s.shift(2)

0    NaN
1    NaN
2    1.0
3    2.0
4    3.0
dtype: float64

In [40]:
s.rolling(4).apply(lambda x:list(x)[-1]-list(x)[0])

0    NaN
1    NaN
2    NaN
3    3.0
4    3.0
dtype: float64

In [41]:
# 类滑窗函数diff()
s.diff(3)

0    NaN
1    NaN
2    NaN
3    3.0
4    3.0
dtype: float64

In [42]:
def my_pct(x):
    L = list(x)
    return L[-1] / L[0] - 1
s.rolling(2).apply(my_pct)

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
dtype: float64

In [43]:
s.pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
dtype: float64

##### 练一练：rolling对象的默认窗口方向都是向下滑动的，某些情况下用户需要逆向滑动的窗口，例如对[1,2,3]设定窗口为2的逆向sum操作，结果为[3,5,NaN]，此时应该如何实现？

In [44]:
s = pd.Series([1,2,3])
s[::-1].rolling(2).sum()[::-1] # 翻转两次

0    3.0
1    5.0
2    NaN
dtype: float64

#### 2.扩张窗口

In [45]:
# 累和操作
s = pd.Series([1,3,6,10])
s.expanding().apply(lambda x:x.sum())

0     1.0
1     4.0
2    10.0
3    20.0
dtype: float64

In [46]:
# 等价于cumsum()
s.cumsum()

0     1
1     4
2    10
3    20
dtype: int64

In [47]:
# 累乘同理
s.expanding().apply(lambda x:x.prod())

0      1.0
1      3.0
2     18.0
3    180.0
dtype: float64

In [48]:
s.cumprod()

0      1
1      3
2     18
3    180
dtype: int64