In [3]:
import numpy as np
import pandas as pd

from pandas.python_base import index

from base.practice5 import index

pd.__version__

'2.3.1'

## 2.1 文件的读取和写入

#### 1.文件读取

In [4]:
# 读取csv文件
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv")
df_csv

   col1 col2  col3    col4        col5
0     2    a   1.4   apple  2020-01-01
1     3    b   3.4  banana  2020-01-02
2     6    c   2.5  orange  2020-01-05

In [26]:
# 读取txt文件
df_txt = pd.read_table("data_base/data/ch2/my_table.txt")
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [4]:
# 读取excel文件
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx")
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.1公共参数

In [6]:
# 公共参数head
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",header=None)
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [7]:
# 公共参数index_col
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",index_col=['col1','col2'])
df_csv

           col3    col4      col5
col1 col2
2    a      1.4   apple  2020/1/1
3    b      3.4  banana  2020/1/2
6    c      2.5  orange  2020/1/5

In [8]:
# 公共参数usecols
df_txt = pd.read_table("data_base/data/ch2/my_table.txt",usecols=['col1','col2'])
df_txt

   col1 col2
0     2    a
1     3    b
2     6    c

In [9]:
# 公共参数parse_dates
df_csv = pd.read_csv("data_base/data/ch2/my_csv.csv",parse_dates=['col5'])
df_csv

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05

In [10]:
# 公共参数nrows
df_excel = pd.read_excel("data_base/data/ch2/my_excel.xlsx",nrows=3)
df_excel

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

##### 1.3 分隔参数

In [13]:
pd.read_table(
    'data_base/data/ch2/my_table_special_sep.txt',
    sep=r'\|\|\|\|',
    engine='python'
)

  col1                 col2
0   TS    This is an apple.
1   GQ      My name is Bob.
2   WT           Well done!

#### 2.2数据写入

In [23]:
# 去除索引
df_csv.to_csv('data_base/data/ch2/my_csv_saved.csv',index=False)
print(open('data_base/data/ch2/my_csv_saved.csv').read())

col1,col2,col3,col4,col5
2,a,1.4,apple,2020-01-01
3,b,3.4,banana,2020-01-02
6,c,2.5,orange,2020-01-05

In [27]:
# 制表
df_txt.to_csv('data_base/data/ch2/my_txt_saved.txt',sep='\t',index=False)
print(open('data_base/data/ch2/my_txt_saved.txt').read())

col1	col2	col3	col4	col5
2	a	1.4	apple	2020/1/1
3	b	3.4	banana	2020/1/2
6	c	2.5	orange	2020/1/5

In [28]:
# 转换成markdown
print(df_csv.to_markdown())

|    |   col1 | col2   |   col3 | col4   | col5                |
|---:|-------:|:-------|-------:|:-------|:--------------------|
|  0 |      2 | a      |    1.4 | apple  | 2020-01-01 00:00:00 |
|  1 |      3 | b      |    3.4 | banana | 2020-01-02 00:00:00 |
|  2 |      6 | c      |    2.5 | orange | 2020-01-05 00:00:00 |

In [6]:
# 转换成latex
print(df_csv.style.to_latex())

\begin{tabular}{lrlrll}
 & col1 & col2 & col3 & col4 & col5 \\
0 & 2 & a & 1.400000 & apple & 2020-01-01 \\
1 & 3 & b & 3.400000 & banana & 2020-01-02 \\
2 & 6 & c & 2.500000 & orange & 2020-01-05 \\
\end{tabular}

## 2.2 基本数据结构

#### 1.Series

In [8]:
# 创建Series对象
s = pd.Series(
    data = [100,'a',{'dic1':5}],
    index = pd.Index(['id1',20,'third'],name='my_index'),
    dtype = 'object',
    name = 'my_name'
)
s

my_index
id1              100
20                 a
third    {'dic1': 5}
Name: my_name, dtype: object

In [10]:
# 获取属性内容
s.values

Index(['id1', 20, 'third'], dtype='object', name='my_index')

In [11]:
s.index

Index(['id1', 20, 'third'], dtype='object', name='my_index')

In [12]:
s.dtype

dtype('O')

In [13]:
s.name

'my_name'

In [14]:
# 获取序列长度
s.shape

(3,)

In [15]:
# 索引取值
s['third']

{'dic1': 5}

#### 2.DataFrame

In [16]:
df = pd.DataFrame(
    data={
        'col_0':[1,2,3],
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=[f'row_{i}' for i in range(3)]
)
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

##### 练一练：在上面的df中，如果data字典中'col_0'键对应的不是列表，而是1个索引与df中索引相同的Series，此时会发生什么？如果它的索引和df的索引不一致，又会发生什么？

In [24]:
# 当索引一致时，序列的值直接对应填入DataFrame。
index = [f'row_{i}' for i in range(3)]
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=index),
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [19]:
# 当索引不一致时且Series中索引值唯一时，当前DataFrame行索引如果在Series中出现，
# 则用Series对应元素填充，否则设为缺失值。
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=['row_3','row_2','row_1']), # Nan、3、2
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df

       col_0 col_1  col_2
row_0    NaN     a    1.2
row_1    3.0     b    2.2
row_2    2.0     c    3.2

In [20]:
# 用[col_name]和[col_list]取出相应的列与由多个列组成的新的DataFrame
df['col_0']

row_0    NaN
row_1    3.0
row_2    2.0
Name: col_0, dtype: float64

In [22]:
# New DataFrame
df[['col_0','col_1']]

       col_0 col_1
row_0    NaN     a
row_1    3.0     b
row_2    2.0     c

##### 练一练：df['col_0']和df[['col_0']]二者得到的结果类型有什么区别？

In [23]:
# 前者是Series，后者是DataFrame
df[['col_0']]

       col_0
row_0    NaN
row_1    3.0
row_2    2.0

In [25]:
# 把序列转换为列数为1的DataFrame
df['col_0'].to_frame()

       col_0
row_0      1
row_1      2
row_2      3

In [26]:
# 对DataFrame的行列进行转置
df.T

      row_0 row_1 row_2
col_0     1     2     3
col_1     a     b     c
col_2   1.2   2.2   3.2

##### 练一练：给定一个DataFrame，请构造其转置且不得使用“.T”。

In [30]:
df = pd.DataFrame(data={'A':[1,2,3],'B':[4,5,6]},index=list('abc'))
df_T = pd.DataFrame(df.values.T, index=df.columns, columns=df.index)
df.T.equals(df_T)

   a  b  c
A  1  2  3
B  4  5  6

##### 修改或删除列

In [36]:
df = pd.DataFrame(
    data={
        'col_0':pd.Series([1,2,3],index=index), # Nan、3、2
        'col_1':list('abc'),
        'col_2':[1.2,2.2,3.2]
    },
    index=index
)
df["col_0"] = df['col_0'].values[::-1] #颠倒顺序
df["col_2"] *= 2
df["col_3"] = ["apple","banana","cat"] #新增一列
df

       col_0 col_1  col_2   col_3
row_0      3     a    2.4   apple
row_1      2     b    4.4  banana
row_2      1     c    6.4     cat

In [37]:
# 删除列
df.drop(["col_3"],axis=1)

       col_0 col_1  col_2
row_0      3     a    2.4
row_1      2     b    4.4
row_2      1     c    6.4

In [38]:
# 删除行
df.drop(["row_1"],axis=0)

       col_0 col_1  col_2  col_3
row_0      3     a    2.4  apple
row_2      1     c    6.4    cat